version: '3.8'

services:
  nginx_with_ba:
    build: http/nginx/nginx-with-ba/.
    ports:
      - "8080:80"
  httpd_with_ba:
    build: http/httpd/httpd-with-ba/.
    ports:
      - "8081:80"
  nginx_with_ba_wrong_creds:
    build: http/nginx/nginx-with-ba-wrong-creds/.
    ports:
      - "8082:80"
  httpd_with_ba_wrong_creds:
    build: http/httpd/httpd-with-ba-wrong-creds/.
    ports:
      - "8083:80"
  nginx_without_ba:
    build: http/nginx/nginx-without-ba/.
    ports:
      - "8084:80"
  httpd_without_ba:
    build: http/httpd/httpd-without-ba/.
    ports:
      - "8085:80"
  nginx_with_ba_https:
    build: https/nginx/nginx-with-ba-https/.
    ports:
      - "8443:443"